# -*- coding: utf-8 -*-
"""SMS Spam Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEVNv4wjfqmC0JjL9MZafT5R5I4VPz2Y
"""


import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import zipfile
import os

ZIP_PATH = "archive.zip"
EXTRACT_DIR = "data"

with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_DIR)

dataset_path = ""
for root, dirs, files in os.walk(EXTRACT_DIR):
    for file in files:
        if file.endswith('.csv') or file.endswith('.tsv'):
            dataset_path = os.path.join(root, file)
            break

df = pd.read_csv(dataset_path, encoding='latin-1')
df = df.rename(columns={df.columns[0]: 'label', df.columns[1]: 'text'})
df = df[['label', 'text']]
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

X = df['text']
y = df['label']

vectorizer = TfidfVectorizer(stop_words='english')
X_vec = vectorizer.fit_transform(X)

model = LogisticRegression()
model.fit(X_vec, y)

st.title("📱 SMS Spam Detection")

st.write("Enter your SMS message below to check whether it's Spam or Not.")

user_input = st.text_area("Type your message here:")

if st.button("Predict"):
    input_vector = vectorizer.transform([user_input])
    prediction = model.predict(input_vector)[0]
    label = "Spam ❌" if prediction == 1 else "Ham ✅"
    st.markdown(f"### Prediction: {label}")
